// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  secureRoutes: ['https://localhost:44321/api', 'https://cat-netcore-api.azurewebsites.net/api'],
  stsServer: 'https://cat-token-identity.azurewebsites.net',
  clientId: 'devkit-clients-spa.pkce',
  scope: 'openid profile email roles app.api.employeeprofile.read',
  Api_Endpoint: 'https://cat-netcore-api.azurewebsites.net/api/v1',
  Api_Mock_Endpoint: 'https://localhost:44321/api',
};
